[package]
name = "raffler"
version = "0.0.1"
edition = "2021"

[dependencies]
rocket = {version = "0.5.0-rc.1", features = ["json"]}
rocket_db_pools = {version = "0.1.0-rc", features = ["sqlx_sqlite"]}
# chrono = { version = "0.4", features = ["serde"]}

[dependencies.sqlx]
version = "0.5.1"
default-features = false
# features = ["chrono", "macros", "offline", "migrate"]
features = ["macros", "offline", "migrate"]

[patch.crates-io]
rocket = { git = "https://github.com/SergioBenitez/Rocket"}
rocket_db_pools= {  git = "https://github.com/SergioBenitez/Rocket"}
