[package]
name = "raffler"
version = "0.0.1"
edition = "2021"
publish = false

[dependencies]
axum = "0.7.5"
futures-util = "0.3"
tokio = { version = "1.0", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

serde = "1.0.202"
serde_json = "1.0.117"
sqlx = { version = "0.7", features = ["runtime-tokio-rustls", "any", "chrono", "postgres"] }
chrono = { version="0.4.38", features = ["serde"]}
