name: Raffler

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable

    - name: Clippy
      continue-on-error: true  # WARNING: only for this example, remove it!
      run: cargo clippy -- -D warnings
    
    - name: Build
      run: cargo build --release --verbose
    
    - name: Run tests
      run: cargo test --color always --all-features
